# .github/workflows/build.yml
name: Build
on: [push, pull_request]
env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9.1.1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm + Node
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          run_install: false
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
