# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node first
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # pnpm second → now at the front of PATH
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.1
          run_install: false     # we'll run install ourselves

      - run: pnpm --version      # should print 9.1.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm test -- --ci
      - run: pnpm run build
