name: CI

on:
  push:
    branches: [main]
  pull_request: {}

env:
  NODE_VERSION: 20          # change if you need another runtime
  PNPM_VERSION: 9.1.1       # must match the "packageManager" field

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # This single step gives us BOTH Node and pnpm
      - name: Setup pnpm + Node
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          run_install: false       # ← DON'T let the action call pnpm for us

      # Cache the pnpm store between runs
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint & type-check
        run: |
          pnpm lint
          pnpm typecheck

      - name: Unit tests
        run: pnpm test

      - name: Build
        run: pnpm build
